name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "action_state=yellow" >> $GITHUB_ENV

      - name: Build
        uses: sulimak-co/docker-action@test-branch
        env:
          TAG: $BRANCH_NAME
        with:
          repository: test-actions/test-actions
          username: ${{ github.repository_owner }}}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          tag: $action_state
