name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Show Branch name
        run: echo $BRANCH_NAME
      
      - name: Build
        uses: sulimak-co/docker-action@test-branch
        env:
          TAG: ${{GITHUB_REF#refs/heads/}}
        with:
          repository: test-actions/test-actions
          username: ${{ github.repository_owner }}}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          tag: ${{env.TAG}}
