name: Test

on:
  push:

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Old way for set env
        run: echo ::set-env name=GITHUB_BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})
        
      - name: New way for set env
        run: echo "action_state=yellow" >> $GITHUB_ENV
        
      - name: Show old env
        run: echo ${{ env.GITHUB_BRANCH_NAME }}

      - name: Show new env
        run: echo $action_state
