name: Test

on:
  workflow_dispatch:
    inputs:
      hello:
        description: 'hello world'
        required: true  
        default: 'world'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "${{ github.event.inputs.hello }}""
